#
# This file is part of the NML build framework
# NML build framework is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
# NML build framework is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with NML build framework. If not, see <http://www.gnu.org/licenses/>.
#

###################################
# Definition of the grf
###################################
REPO_NAME          := HEQS (Heavy Equipment Set)

# Filename part common to the grf file, main source file and tar file
BASE_FILENAME  := heqs

GRF_ID             := \"AP\" 12 02

####################################
# Directory and filename definitions
####################################
# Directory structure
SRC_DIR        ?= sprites/nfo
SCRIPT_DIR     ?= scripts

# Filename of the nfo file
NFO_FILE       ?= $(BASE_FILENAME).nfo

# Source file for preprocessing
MAIN_SRC_FILE  ?= $(SRC_DIR)/$(BASE_FILENAME).pnfo


GENERATE_GRF   ?= nfogrf
GENERATE_NFO   ?= nfo

-include Makefile.local

################################################################
# Programme definitions / search paths
################################################################
NFORENUM       ?= nforenum
NFORENUM_FLAGS ?= $(shell [ `$(NFORENUM) -s -v 2>/dev/null | wc -l ` -eq 1 ] && echo "-s" || echo "")

GRFCODEC       ?= grfcodec
GRFCODEC_FLAGS ?= $(shell $(GRFCODEC) -s -v >/dev/null 2>/dev/null && echo "-s" || echo "") -e -p 2 -c
