# Settings for the Makefile which define
# various things like the names, paths, etc pp
#
# 

# The displayed name of the newgrf. Replace the name string
# in action 08 by {{GRF_NAME}}
GRF_NAME        = HEQS (Heavy Equipment Set)
# The filename of the GRF (without extension)
FILENAME        = heqs
# Description of the newgrf. Can be in header.pnfo, too
# GRF_DESCRIPTION = my nice and lenghty description

# the filename of the bundle for none-release builds
GRF_NIGHTLYNAME = nightly


################################################################
#suffixes of the files used
################################################################
# extension of the source code files
# don't name it nfo but something else
PNFO_SUFFIX = pnfo

# Suffix of the pre-processed nfo file:
CPNFO_SUFFIX = cpnfo

# other relevant extensions. Normally it's not necessary to edit these
NFO_SUFFIX = nfo
GRF_SUFFIX = grf
TAR_SUFFIX = tar
BZ2_SUFFIX = bz2
ZIP_SUFFIX = zip
PCX_SUFFIX = pcx

################################################################
# Programme definitions / search paths
################################################################
# Build parameters and programmes
NFORENUM_FLAGS = 
GRFCODEC_FLAGS = -e -p 2
TAR_FLAGS      = cf
ZIP_FLAGS      = -r
BZIP_FLAGS     = -k9f

NFORENUM = renum
GRFCODEC = grfcodec
TAR      = tar
ZIP      = zip
BZIP     = bzip2

################################################################
# Paths defining the directory layout
################################################################

# Paths defining the directory layout
# directory containing the sprites (pnfo and pcx files)
#
# Generally the structure is expected to look like this
# <main>
# |-sprites
# | |-nfo
# | | |-header.pnfo
# | | |-subdir
# | | | |-somefile.pnfo
# | | |-langdir
# | | | |-english.pnfo
# | |-pcx
# |   |-images.pcx
# |   |-subdir
# |     |-somefile.pcx
# |-docdir
# | |-readme.txt
# | |-license.txt
# | |-changelog.txt
# |-website
# |-scripts
# |-Makefile
# |-Makefile.config

SPRITEDIR   = sprites
DOCDIR      = docs
WEBDIR      = website
NFODIR      = $(SPRITEDIR)
MAINDIRS    = $(SPRITEDIR) $(DOCDIR) $(WEBDIR)

################################################################
# Filenames which comprise the grf
################################################################
# Now come the definitions of the files which comprise the newgrf:
# Filenames to include in the grf in sprites/nfo
# HEADER goes first, FOOTER goes last. The others are 
# placed behind header and before engines and language files.
HEADER      = heqs_header
OTHERS      = 
FOOTER      = 

# Names of the subdirectories (if applicable) where all *.pnfo files will be used, too
# these directories are relative to sprites/nfo
# These files will be inserted before the footer
NFO_SUBDIRS = 

# if they're the same as NFO_SUBDIRS, use
# PCXSUB_DIRS = $(NFO_SUBDIRS)
PCX_SUBDIRS = 

# The language directory. All nfo files from there will be
# put into the final grf. It is relative to sprites/nfo
# These files will be inserted before the footer
LANG_DIR       = 
LANGUAGE_FILES = 

# Documentation files with relative path. Usually they should be in $(DOCDIR).
LICENSEFILE = $(DOCDIR)/license.txt
READMEFILE  = $(DOCDIR)/readme.pdf
CHANGELOG   = $(DOCDIR)/readme.txt

DOCUMENTATION = $(LICENSEFILE) $(READMEFILE) $(CHANGELOG)

################################################################
# Rules on how to generate filenames. Usually no need to change
################################################################
# Define how the displayed name and the filename of the bundled grf shall look like:
# The result will either be
# nightly build:                   mynewgrf-nightly-r51
# a release build (tagged version): mynewgrf-0.1
# followed by an M, if the source repository is not a clean version.
# Define how the displayed name and the filename of the bundled grf shall look like:
BUILDFILENAME = $(FILENAME)-$(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(GRF_MODIFIED) || echo $(GRF_NIGHTLYNAME))
DIR_NAME      = $(BUILDFILENAME)

TAR_FILENAME   = $(BUILDFILENAME).$(TAR_SUFFIX)
BZIP_FILENAME  = $(BUILDFILENAME).$(BZ2_SUFFIX)
ZIP_FILENAME   = $(BUILDFILENAME).$(ZIP_SUFFIX)
NFO_FILENAME   = $(SPRITEDIR)/$(addsuffix .$(NFO_SUFFIX),$(FILENAME))
CPNFO_FILENAME = $(SPRITEDIR)/$(addsuffix .$(CPNFO_SUFFIX),$(FILENAME))
GRF_FILENAME   = $(addsuffix .$(GRF_SUFFIX),$(FILENAME))

# Files to include in a release (e.g. to pack into tar, zip, files)
BUNDLE_FILES  = $(GRF_FILENAME) $(DOCUMENTATION)

# Adding the proper paths to the files which comprise the newgrf
# Normally this need not be changed
HEADER_FILE   = $(addsuffix .$(PNFO_SUFFIX),$(NFODIR)/$(HEADER))
FOOTER_FILE   = $(shell [ -n "$(FOOTER)" ] && echo "$(addsuffix .$(PNFO_SUFFIX),$(NFODIR)/$(FOOTER))")
OTHER_FILES   = $(shell [ -n "$(OTHERS)" ] && echo "$(addsuffix .$(PNFO_SUFFIX),$(addprefix $(NFODIR)/,$(OTHERS)))")
LANG_FILES    = $(shell [ -n "$(LANG_DIR)" ] && echo "$(wildcard $(NFODIR)/$(LANG_DIR)/*.$(PNFO_SUFFIX))")
NFO_SUBFILES  = $(shell [ -n "$(NFO_SUBDIRS)" ] && echo "$(foreach dir,$(NFO_SUBDIRS),$(wildcard $(NFODIR)/$(dir)/*.$(PNFO_SUFFIX)))")
PCX_FILES     = $(shell [ -n "$(PCX_SUBDIRS)" ] && echo "$(foreach dir,$(PCX_SUBDIRS),$(wildcard $(PCX_DIR)/$(PCX_SUBDIRS)/*.$(PCX_SUFFIX)))")

################################################################
# the displayed name within OpenTTD / TTDPatch
################################################################
# Looks like either
# a nightly build:                 GRF's Name nightly-r51
# a release build (taged version): GRF's Name 0.1
GRF_TITLE    = $(GRF_NAME) $(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(GRF_MODIFIED) || echo $(GRF_NIGHTLYNAME)-r$(GRF_REVISION)$(GRF_MODIFIED))

